version: '2'
services:
  app:
    build: .
    command: yarn lerna run dev --scope @marvel/app
    ports:
      - "3000:3000"
    environment:
      REACT_APP_SERVER_URL: 'http://localhost:4000'
  server:
    build: .
    command: yarn lerna run dev --scope @marvel/server
    ports:
      - "4000:4000"
